---
title: "Biography"
---

My academic trajectory is a bit unconventional. Over the past 15 years I have transitioned from a researcher in neuroscience of memory to a broader behavioural scientist.

I completed my undergraduate BSc in Psychology at Cardiff University in 2006, where I went onto undertake my doctoral thesis on _Electrophysiological Correlates of Individual Differences in Strategic Retrieval Processing_ supervised by [Professor Ed Wilding](https://www.birmingham.ac.uk/staff/profiles/psychology/wilding-edward.aspx).

From 2010-2014, I worked as scientific researcher (Wissenschaftlicher Mitarbeiterin) and lecturer at the Universitaet des Saarlandes Experimentelle Neuropsychologie Unit, with [Professor Dr Axel Mecklinger](http://www.neuro.psychologie.uni-saarland.de/pages/staff/staff_lebenslauf/mecklinger.html). 

In 2014, I completed an MSc in Behavioural Sciences at the University of Stirling Management School. I have worked as a Research Fellow at Birmingham City University in the Department of Psychology since August 2015, where I am a member of the School of Social Sciences [Research Centre for Lifespan and Behavioural Science](https://www.bcu.ac.uk/social-sciences/research/lifespan-and-behavioural-science#:~:text=Investigating%20and%20developing%20understanding%20of,emotional%20development%20throughout%20the%20lifespan.).

