---
title: "Peer-reviewed Publications"
---

<p>&nbsp;</p>
  
**Bridger, E.** & Lally, H. (2022). Rewarding valuable services and altruistic motives: Gratitude and pay for essential workers during the Covid-19 pandemic. _Journal of Social Psychology_  
  
**Bridger, E. K.** & Nettle, D. (2022). [Public perceptions of the effectiveness of income provision on reducing psychological distress](http://www.open-access.bcu.ac.uk/id/eprint/13262). _Journal of Public Mental Health, 21_(3), 208-217. https://doi.org/10/1108/JPMH-04-2022-0036. 

Aldrovandi, S., **Bridger, E. K.**, Knowles, D. & Poirier, M. (2022). [Retrospective and prospective evaluations of mammograph screening narratives: The role of own experience](http://www.open-access.bcu.ac.uk/id/eprint/13293). _Experimental Psychology_. 

**Bridger, E. K.** & Daly, M. (2020). [Intergenerational social mobility predicts midlfe well-being: Prospective evidence from two large British Cohorts](http://www.open-access.bcu.ac.uk/9522/). _Social Science & Medicine, 261_, 113217 DOI: 10.1016/j.socscimed.2020.113217.

**Bridger, E. K.** & Daly, M. (2018). [Cognitive ability as a moderator of the association between social disadvantage and psychological distress: evidence from a population-based sample](https://doi.org/10.1017/S0033291718002118). _Psychological Medicine, 1-10_, DOI: 10.1017/S0033291718002118.

**Bridger, E. K.** & Daly, M. (2017). [Does cognitive ability buffer the link between childhood disadvantage and adult health?](http://bcu-test.eprints-hosting.org/6165/1/Cognitive%20ability%20as%20moderator_AM%2BSupple.pdf) _Health Psychology, 36_(10), 966-976. doi: 10.1037/hea0000538 

**Bridger, E. K.**, Kursawe, A-L., Bader, R., Tibon, R., Gronau, N., Levy, D. & Mecklinger, A. (2017). [Age effects on associative memory for novel picture pairings](http://www.open-access.bcu.ac.uk/4560/). _Brain Research, 1664_, 102-115.https://doi.org/10.1016/j.brainres.2017.03.031

**Bridger, E. K.** & Wood, A. (2017). [Gratitude mediates consumer responses to marketing communications](http://www.open-access.bcu.ac.uk/3396/). _European Journal of Marketing, 51_ (1), 44-64. https://doi.org/10.1108/EJM-11-2015-0810

Studte, S., **Bridger, E. K.**, & Mecklinger. A. (2016). [Sleep spindles during a nap correlate with post sleep memory performance for highly rewarded word-pairs](http://www.open-access.bcu.ac.uk/3398/). _Brain & Language, 167_, 28-35. https://doi.org/10.1016/j.bandl.2016.03.003 

Bai, C-H., **Bridger, E. K.**, Zimmer, H., & Mecklinger, A. (2015). [The beneficial effect of testing: An event-related potential study]. _Frontiers in Behavioral Neuroscience, 9_, 248. doi:10.3389/fnbeh.2015.00248

Studte, S., **Bridger, E. K.**, & Mecklinger. A. (2015). [Nap sleep preserves associative but not item memory performance](http://www.open-access.bcu.ac.uk/3398/1/Studte_B%26L_accepted.pdf). _Neurobiology of Learning and Memory, 120_, 84-93. https://doi.org/10.1016/j.nlm.2015.02.012

**Bridger, E. K.**, Sprondel, V. & Mecklinger, A. (2015). [Control over Recollection varies with Context-Type: ERP Evidence from the Exclusion Task](http://bcu-test.eprints-hosting.org/4631/). _Cognitive Neuroscience, 6_(1), 31-38. https://doi.org/10.1080/17588928.2014.996211

Scheuplein, A-L., **Bridger, E. K.** & Mecklinger, A. (2014). [Is faster better? Effects of response deadline on ERP correlates of recognition memory in young and older adults](http://www.open-access.bcu.ac.uk/4632/). _Brain Research, 1582_, 139-153.https://doi.org/10.1016/j.brainres.2014.07.025

**Bridger, E. K.**, Bader, R. & Mecklinger, A. (2014). [More ways than one: ERPs reveal multiple familiarity signals in the word frequency mirror effect](http://www.open-access.bcu.ac.uk/4633/). _Neuropsychologia, 57_, 179-190. https://doi.org/10.1016/j.neuropsychologia.2014.03.

**Bridger, E. K.** & Mecklinger, A. (2014). [Errorful and errorless learning: The impact of cue-target constraint in learning from errors](http://www.open-access.bcu.ac.uk/4634/). _Memory & Cognition, 42_(6), 898-911. https://doi.org/10.3758/s13421-014-0408-z

Kriukova, O., **Bridger, E. K.** & Mecklinger, A. (2013). [Semantic relations differentially impact associative recognition memory: Electrophysiological evidence]. _Brain & Cognition, 83_(1), 93-103. https://doi.org/10.1016/j.bandc.2013.07.006

**Bridger, E. K.**, Bader, R., Kriukova, O., Unger, K. & Mecklinger, A. (2012). The FN400 is functionally distinct from the N400. _NeuroImage, 63_, 1334-1342. doi: 10.1016/j.neuroimage.2012.07.047

Halsband, T. M., Ferdinand, N. K., **Bridger, E. K.**, & Mecklinger, A. (2012). Monetary rewards influence retrieval orientations. _Cognitive, Affective & Behavioral Neuroscience, 12_(3), 430-445. doi: 10.3758/s13415-012-0093-y

**Bridger, E. K.** & Mecklinger, A. (2012). Electrophysiologically dissociating episodic preretrieval processing. _Journal of Cognitive Neuroscience, 24_(6), 1476-1491. doi: 10.1162/jocn_a_00152

**Bridger, E. K.** & Wilding, E. L. (2010). Requirements at retrieval modulate subsequent memory effects: An event-related potential study. _Cognitive Neuroscience, 1_, 254-260. https://doi.org/10.1080/17588928.2010.484882

**Bridger, E. K.**, Herron, J. E., Elward, R. L., & Wilding, E. L. (2009). Neural correlates of individual differences in strategic retrieval processing. _Journal of Experimental Psychology: Learning, Memory & Cognition, 35_ _(5), 1175-1186.
