---
title: "Research Projects"
---
<p>&nbsp;</p>

Some of my current research projects include:

*Perceived Causal Relations of Determinants of Health: Adapting Network Analytic Approaches* 

This present project is funded by a British Academy Talent Development Award. The Award employs network analysis - set of statistical techniques that enable analysis and visualisation of relational data - to develop new methods to assess perceived causal relations between the social determinants of health and a range of health outcomes. This is important not only because of the inherent complexity of social determinants of health but because people's causal intuitions often overlook structural determinants of health in favour of biological or lifestyle causes. 

*Stressful politics: Understanding politics as a stress factor for mental health* 

Together with Dr Luca Bernardi (University of Liverpool) and Professor Jonathan Roiser (University College London), this project examines how people's appraisals of the broader political climate relates to poorer mental health over time. Increasing political polarisation and political hostility represent just one aspect of the present global polycrisis, but that which is most related to the mechanisms to deal with and address these crises. Here we focus on the mental health consequences of finding the present political stressful and how we can use this to protect mental health whilst encouraging people not to disengage from politics.

You can learn more about this project [here](https://www.youtube.com/watch?v=Dh3tq7yYeVE). 

<p>&nbsp;</p>
<p>&nbsp;</p>

#### Previous Funded Research Projects

*A new approach to documenting public opinion of health inequalities in the United Kingdom and United States* 

This project was funded by a BA/Leverhulme Small Research grant to employ different methods to capture views of the UK and US public on health inequality. Part of this includes the use of a novel objective and easy-to-interpret measure of the public's perceived and desired levels of health inequality. 

Attention during risky decision-making: Insights from eye movements and neural modelling  
_British Academy/Leverhulme Small Research Grant_