---
title: "Teaching + Other Activities"
---
<p>&nbsp;</p>
  
*What else am I up to?*

I have a lot of fun teaching Quantitative Research Methods on the [MSc Psychology online conversion course](https://www.bcu.ac.uk/courses/psychology-msc-2021-22) where we pack the fundamentals of quantitative methods into a single semester! I also teach on psychology modules across levels 4-7 including Contemporary Issues in Psychology, Brain and Cognition, Advanced Research Methods. I have been very involved in organising, chairing and reviewing undergraduate, postgraduate, PhD and staff project ethics applications for the past 6 years. 

I am a SEDA-qualified doctoral supervisor and part of the supervisory team for a number of funded PhD students. If you are interested in a PhD, particularly behavioural science projects that lie at the intersection between cognition, social inequality and health, do get in touch.

I am a member of the following networks and organisations:  
* [British Psychological Society](https://www.bps.org.uk/)  
* [Psychologists for Social Change](http://www.psychchange.org/)  
* [Medact Economic Justice and Health](https://www.medact.org/membership/groups/economic-justice-health/)  

Related outputs include:

[Fair’s fair? What should psychologists understand about austerity, and ways to broaden the role of psychologists in order to combat its effects? Insights from ‘Make My City Fair’ in Birmingham](https://thepsychologist.bps.org.uk/volume-34/summer-edition/fairs-fair)  
[Health Versus Wealth? UK economic policy and public health during COVID-19](https://www.medact.org/2021/resources/briefings/health-versus-wealth-uk-economic-policy-and-public-health-during-covid-19/)
